CONNECT 'jdbc:derby:service;create=true';
AUTOCOMMIT OFF;
CREATE TABLE SEEDS (
	SEED_ID INTEGER NOT NULL
);
ALTER TABLE SEEDS ADD CONSTRAINT SEEDS_PK Primary Key (SEED_ID);
INSERT INTO SEEDS VALUES (9);
COMMIT;





CONNECT 'jdbc:derby:people;create=true';
AUTOCOMMIT OFF;

CREATE TABLE MEMBERS (
	MEMBER_ID INTEGER NOT NULL,
	MEMBER_NAME VARCHAR(50) NOT NULL,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	DISPLAY_NAME VARCHAR(150) NOT NULL,
	COMMENT VARCHAR(200) NOT NULL
);


ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_PK Primary Key (MEMBER_ID);
ALTER TABLE MEMBERS ADD CONSTRAINT MEMBER_NAME_UNQ Unique (MEMBER_NAME);

INSERT INTO MEMBERS VALUES (1,'jhop','John','Hopkins','John Hopkins','Ministre de delicte');
INSERT INTO MEMBERS VALUES (2,'groul','Gerard','Ruleta','Gerard Ruleta','Ministre de seguretat i intelligencia');
INSERT INTO MEMBERS VALUES (3,'inaka','Iori','Nakamura','Iori Nakamura','Coordinador');
INSERT INTO MEMBERS VALUES (4,'gvlk','Grndal','Vlkoff','Grndal Vlkoff','Jutge suprem triat');

COMMIT;







CONNECT 'jdbc:derby:auth;create=true';

AUTOCOMMIT OFF;


CREATE TABLE CREDENTIALS (
	CREDENTIALS_ID INTEGER NOT NULL,
	MEMBER_NAME VARCHAR(256) NOT NULL,
	PASSWORD VARCHAR(256) NOT NULL
);
ALTER TABLE CREDENTIALS ADD CONSTRAINT CREDENTIALS_PK Primary Key (CREDENTIALS_ID);
ALTER TABLE CREDENTIALS ADD CONSTRAINT MEMBER_NAME_UNQ Unique (MEMBER_NAME);

INSERT INTO CREDENTIALS VALUES (5,'jhop','Hopkins');
INSERT INTO CREDENTIALS VALUES (6,'groul','Ruleta');
INSERT INTO CREDENTIALS VALUES (7,'inaka','Nakamura');
INSERT INTO CREDENTIALS VALUES (8,'gvlk','Vlkoff');


CREATE TABLE AUTHORIZATIONS (
	AUTHORIZATION_ID INTEGER NOT NULL,
	CREDENTIALS_ID INTEGER NOT NULL,
	TOKEN VARCHAR(256) NOT NULL,
	CREATED_TIME BIGINT NOT NULL,
	EXPIRED_TIME BIGINT NOT NULL
);
ALTER TABLE AUTHORIZATIONS ADD CONSTRAINT AUTHORIZATIONS_PK Primary Key (AUTHORIZATION_ID);


COMMIT;
