
CONNECT 'jdbc:derby:people;create=true';
AUTOCOMMIT OFF;

CREATE TABLE MEMBERS (
	MEMBER_ID INTEGER NOT NULL,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	DISPLAY_NAME VARCHAR(150) NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL
);


ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_PK Primary Key (MEMBER_ID);

COMMIT;

//------------------------------------
CONNECT 'jdbc:derby:auth;create=true';

AUTOCOMMIT OFF;


CREATE TABLE CREDENTIALS (
	CREDENTIAL_ID INTEGER NOT NULL,
	MEMBER_ID INTEGER NOT NULL,
	PASSWORD VARCHAR(256) NOT NULL
);
ALTER TABLE CREDENTIALS ADD CONSTRAINT CREDENTIALS_PK Primary Key (CREDENTIAL_ID);
ALTER TABLE CREDENTIALS ADD CONSTRAINT MEMBER_ID_UNK Unique (MEMBER_ID);


CREATE TABLE AUTHORIZATIONS (
	AUTHORIZATION_ID INTEGER NOT NULL,
	CREDENTIAL_ID INTEGER NOT NULL,
	TOKEN VARCHAR(256) NOT NULL,
	CREATED_TIME DOUBLE PRECISION NOT NULL,
	REMOVED_TIME DOUBLE PRECISION NOT NULL,
	IS_CURRENT BOOLEAN
);
ALTER TABLE AUTHORIZATIONS ADD CONSTRAINT AUTHORIZATIONS_PK Primary Key (AUTHORIZATION_ID);
ALTER TABLE AUTHORIZATIONS ADD CONSTRAINT CREDENTIAL_ID_UNK Unique (CREDENTIAL_ID);


COMMIT;
